# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo version $TF_VAR_SOURCE_VERSION
  displayName: 'show the version'
  env: 
    TF_VAR_SOURCE_VERSION: $(Build.SourceVersion)

- script: |
    echo "running terraform version to ensure we have the used version in the logfile"
    terraform version

    echo "running terraform init to ensure all providers are being initialized"
    terraform init

    echo "Running terraform plan to ensure we have a plannend action shown in the logs"
    terraform plan

  displayName: 
    'Oracle OCI Terraform deployment'
  workingDirectory: 
    "./deployment/environment/terraform/"
  env: 
    TF_VAR_SOURCE_VERSION: $(Build.SourceVersion)



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
