# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo version $TF_VAR_SOURCE_VERSION
  displayName: 'show the version'
  env: 
    TF_VAR_SOURCE_VERSION: $(Build.SourceVersion)

- script: |
    terraform init
    terraform version
  displayName: 'terraform'
  env: 
    TF_VAR_SOURCE_VERSION: $(Build.SourceVersion)



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
